### ISSUE TITLE
Unsupport statement in flux.py

### ISSUE THREAD

**Issue by wilke** [ExaWorks/psi-j-python#123]
I tried to install psi-j-python by running `make install` and got the error below. I suggest upgrading to python 3.7 or removing the __future__ statement 

`creating`` /gpfs/fs1/home/wilke/anaconda3/envs/psi-j/lib/python3.6/site-packages/psi_j_python-0.1-py3.6.egg
Extracting psi_j_python-0.1-py3.6.egg to /gpfs/fs1/home/wilke/anaconda3/envs/psi-j/lib/python3.6/site-packages
  File "/gpfs/fs1/home/wilke/anaconda3/envs/psi-j/lib/python3.6/site-packages/psi_j_python-0.1-py3.6.egg/psij/executors/flux.py", line 3
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined`

**Comment by hategan** [comment]
A bit of a side note. annotations from __future__ was introduced in 3.7. It's my understanding that it is used to declare types of variables in the following form: `<name>: <type> = <value>`. However, it is still possible to achieve the same goal with `<name> = <value>  # type: <type>`. While the former syntax appears more appropriate, it may not be sufficient of a reason to require 3.7 instead of 3.6.

**Comment by jameshcorbett** [comment]
Python 3.6 [reached its EOL at the end of 2021](https://endoflife.date/python), so I think we can safely upgrade to 3.7.

**Comment by hategan** [comment]
It may have reached EOL, but that doesn't mean it's not used. See, e.g., https://pypistats.org/packages/__all__, https://w3techs.com/technologies/details/pl-python/3.

I think it would be reasonable to bump the minimum version if we were quite sure it is not used any more and/or the cost of maintaining compatibility was high. But I don't think either of those things are true here.
